<?php

/**
 * @file
 * Contains yext.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function yext_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the site_branding_per_role module.
    case 'help.page.yext':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Yext Answers is a revolutionary site search product that understands natural language and puts dynamic answers on your website to help consumers convert — right in the search results.') . '</p>';
      return $output;

    default:
  }
}
